### ISSUE TITLE
Error on Flutter Web

### ISSUE THREAD

**Issue by lucioeduardo** [SandroMaglione/fpdart#12]
I got this error trying to compile to chrome:

`
../../../../../.pub-cache/hosted/pub.dartlang.org/fpdart-0.0.6/lib/src/typeclass/group.dart:3:28: Error: The integer literal 9223372036854775807 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 9223372036854775808 is the nearest value that can be represented exactly.
const int _int64MaxValue = 9223372036854775807;
                           ^^^^^^^^^^^^^^^^^^^
Failed to compile application.
`

Searching, i found it from https://api.dart.dev/stable/2.12.4/dart-core/int-class.html:
> **Note:** When compiling to JavaScript, integers are restricted to values that can be represented exactly by double-precision floating point values. The available integer values include all integers between -2^53 and 2^53, and some integers with larger magnitude. That includes some integers larger than 2^63.

It successfully compiled when i changed `_int64MaxValue` to 2^53. Is it a viable solution?

**Comment by SandroMaglione** [comment]
Hi @lucioeduardo 

Yes, it has to do with [_int64MaxValue](https://github.com/SandroMaglione/fpdart/blob/d7300e3d20005dc05ce64e9323881fd5c255d47a/lib/src/typeclass/group.dart#L3) in `group.dart`. Nonetheless, considering this error, I am going to remove the `_int64MaxValue` constant since it does not provide any meaningful API functionality.

Thanks for reporting this issue 😁
