### ISSUE TITLE
Anchors in menu of readme file doesn't work

### ISSUE THREAD

**Issue by ChessMax** [SandroMaglione/fpdart#137]
Clicking on Task doesn't scroll to task subsection.

**Comment by SandroMaglione** [comment]
This is an issue with pub.dev. The anchors work on the Github page.

The anchor id on pub.dev is different: [https://pub.dev/packages/fpdart#taskpackagesfpdartlibsrctaskdart](https://pub.dev/packages/fpdart#taskpackagesfpdartlibsrctaskdart)
 
It contains `#taskpackagesfpdartlibsrctaskdart` instead of simply `#task`. Opened an issue to solve this on dart's sdk.

**Comment by SandroMaglione** [comment]
Closed since this is not related to `fpdart`. Waiting for a fix on dart pub.
