### ISSUE TITLE
FP Loops and Dart

### ISSUE THREAD

**Issue by TheOnlyNurse** [SandroMaglione/fpdart#16]
Given [#29](https://github.com/dart-lang/sdk/issues/29), how do I implement loops in a functional way?

I've been stumped on this for a while and since the functional programming sect of Dart seems to be small, I've yet to find any answers that have been relevant to my Flutter app. From my understanding, the lack of tail recursion optimisation means that the using recursive functions in general (especially for large datasets or small stacks on constrained devices) has a chance of making my app misbehave or perform poorly.

Here's a small example of a loop I'd like to get rid of (it's riddle with side effects).

```dart
    while (cacheSize > maxSize) {
      final fileSize = await _deleteOldestFile();
      cacheSize = cacheSize - fileSize;
    }
```

P.S. Sorry if this is the wrong place for this.

**Comment by SandroMaglione** [comment]
Hi @TheOnlyNurse 

The performance of a recursive function may vary based on the specific implementation of the method you use.
The most suitable way I see to convert your code example to functional is to use a recursive call. I do not know if there may be another more performant solution.

I am going to close the issue since it is not related to fpdart. Feel free to comment if you have any other doubt.

**Comment by TheOnlyNurse** [comment]
Thanks for your time @SandroMaglione, I appreciate it
