### ISSUE TITLE
The return type 'Null' isn't a 'Failure', as required by the closure's context

### ISSUE THREAD

**Issue by Helzio** [SandroMaglione/fpdart#17]
I have an `Either` returning a `Failure` or `Unit`.
If the `either` is `left` I want to extract the `left` value (the `Failure`) and pass it to a method to show that `failure` to the user.

**How can I extract the `left` value from `Either` directly?**
`.getLeft()` returns an `Option`, and `.getOrElse(() => null)` says **The return type 'Null' isn't a 'Failure', as required by the closure's context**

This is my code:
```dart
if (either.isLeft()) {
   final failure = either.getLeft().getOrElse(() => null);
   showSnackbarFromFailure(failure);
}
```

What is the right way to archive that?
Thank you for reading.

PD. If this is not the place to public this I will to delete this issue asap.

**Comment by SandroMaglione** [comment]
Hi @Helzio 

The `Either` type wants to provide a complete type-safe API. `.getLeft()` returns an `Option` because `Either` can be a `Right`, and therefore the left value may be missing.

Generally, when using a `Either` you would have to handle both the `Left` and `Right` cases (using `.match()`) in order to avoid runtime problems when you encounter unexpected situations.

If you really need to handle only the left case, then you can use the following code:
```dart
final Either<String, Unit> either = Either.of(unit);
if (either is Left<String, Unit>) {
  final message = either.value;
  showSnackbarFromFailure(message);
}
```

**Comment by Helzio** [comment]
@SandroMaglione Thank you for the quick response. I will to use the `.mach()` method.
