### ISSUE TITLE
Tuple3,4,5,6

### ISSUE THREAD

**Issue by erabti** [SandroMaglione/fpdart#23]
What about we have Tuple3-6 or 8 as in this package https://pub.dev/packages/tuple.
I can still do something hacky like Tuple2<First, Tuple2<Second, Third>> but it will be not very friendly.

**Comment by SandroMaglione** [comment]
Hi @erabti 

I am not convinced that having and using Tuple3-8 would be a good idea. `Tuple2` is usable in some usecases because it is simple and it avoids creating new classes. Tuple3-8 would be more difficult to read and manage. I think you would be better off creating a new class instead of using Tuple > 2.

Let me know what you think

**Comment by SandroMaglione** [comment]
Closing for now, feel free to comment below for any opinion or idea 👍

**Comment by jibbers42** [comment]
Using Glados propery-based testing (https://pub.dev/packages/glados), I have a class that has more than 10 parameters (the max Glados supports directly). Due to this, I need to generate data in two steps, a Tuple10 and a Tuple4 in my case, then use both to build my class. I'm converting from dartz and the current implementation is using their Tuples.

I going to create a class, and I guess it's not a big deal, but this is the only place I'll use it... as a one-off for a test. I don't use Tuples often (more so in c# where the items can be named), but it is convenient to have them when a good use case comes up.

**Comment by SandroMaglione** [comment]
@jibbers42 the dart team is discussing [adding Records to the language](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#multiple-returns). This would allow to avoid classes like `Tuple`.

Based on this, I think is better to wait. If/When Records come `Tuple` will be no more necessary anyway.
