### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by KristianBalaj** [SandroMaglione/fpdart#35]
There is a comparison to dartz package that states that the fpdart is richer.

However, fpdart does not provide the core typeclasses like monoid, functor, applicative or monoid 🤔

On the other hand, I'm not sure if all this typeclasses can be effectively used in OO language like dart.
Also, I was not able to use these typeclasses from dartz either.
I wanted to use monoid on my data class, however it was already extending equatable so it was not possible to be used since the dartz package made the monoid a class that needs to extended.

I think that these typeclasses could be implemented in dart using double dispatch to overcome such problem.

**Comment by SandroMaglione** [comment]
Hi @KristianBalaj 

`fpdart` has a [typeclass folder](https://github.com/SandroMaglione/fpdart/tree/main/lib/src/typeclass) that contains all the typesclasses that form the core of the package. In fact, every major type (`Option`, `Either`, `Task`, etc.) [extends from this typeclasses](https://github.com/SandroMaglione/fpdart/blob/d253097d7bd40f1d311e29b058b73c213fe2f03a/lib/src/either.dart#L28).

`fpdart` provides also a [`Monoid`](https://github.com/SandroMaglione/fpdart/blob/d253097d7bd40f1d311e29b058b73c213fe2f03a/lib/src/typeclass/monoid.dart#L22) typeclass. You can use it like this:

```dart
class CustomMonoid extends Monoid<int> {
  @override
  int combine(int x, int y) {
    // TODO: implement combine
    throw UnimplementedError();
  }

  @override
  // TODO: implement empty
  int get empty => throw UnimplementedError();
}
```
or using `instance`:
```dart
final instance = Monoid.instance<String>('', (a1, a2) => '$a1$a2');
```

If instead you cannot use `extends` because you are already extending Equatable, in some cases you can use `with`:
```dart
class CustomMonoid extends Equatable with Monoid<int>
```

Let me know if you have a more specific use case and if I can help
