### ISSUE TITLE
Either when, whenLeft and whenRight

### ISSUE THREAD

**Issue by DevNico** [SandroMaglione/fpdart#36]
Should work like fold but not return anything. Basically just execute code in these circumstances.

**Comment by SandroMaglione** [comment]
Hi @DevNico 

It is better to avoid having a `whenLeft`/`whenRight` because they are potentially unsafe. The reason of using `fold` is that you are required to handle both the `Left` and `Right` case. With `whenRight` instead the function risks to become partial:
> When a function is not able to produce a return for every single variable input data given to it then that function is termed as **Partial function**

A partial function is unsafe and potentially impure, which goes against the principles of fp.

I would suggest to use `isLeft`/`isRight` if you need this kind of behaviour instead.

Let me know if you need any other clarification
