### ISSUE TITLE
Unwrap variants for Option and Either

### ISSUE THREAD

**Issue by davidmartos96** [SandroMaglione/fpdart#66]
Hello!
It would be great if there was a way to extract/unwrap the value contained in the Option and Either types.
The unwrap terminology is used in Rust, and given that Dart is not a pure functional language sometimes it's useful to extract the value once you've checked it with `isSome` or `isRight` to do early returns.
For instance say you return Left and you want to launch an error dialog (Flutter). You would want to break the flow of the program to show this dialog, else continue with the regular flow unwrapping the value of Right.

Here is the API in Rust for reference
For Rust Option -> https://doc.rust-lang.org/std/option/#extracting-the-contained-value
For Rust Result (equivalent to Either) -> https://doc.rust-lang.org/std/result/#extracting-contained-values

**Comment by SandroMaglione** [comment]
Hi @davidmartos96 

`fpdart` has the following API to unwrap a value inside `Option` (and `Either`):
- `getOrElse` ([`unwrap_or`](https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_or))
- `match` (equivalent to pattern matching)

In dart there is not a `Default` trait, so it's not possible to have methods like [`unwrap_or_default`](https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_or_default).

Also, `fpdart` intentionally avoids adding methods that `throw` (or `panic` in Rust) to require users to handle the error properly.

Lastly, currently in dart is not possible to narrow the type of `Option` to `Some` after checking `isSome`. Therefore, in order to unwrap the value you should either use `match` or test the value as `Some`:
```dart
final match = option.match(
  () => print('None'),
  (a) => print('Some($a)'),
);

if (option is Some) {
  option.value;
}
```

Does this work for your usecase?

**Comment by davidmartos96** [comment]
@SandroMaglione  Thanks for the example. 
On my use case I'm using Either and I had to do the following "hack" in order to support extracting the contained value in "Right". Is there a better way to do it?
Note that in this situation I want to early return an enum with the reason when a Left is returned.

```dart
  Future<SomeResult?> _doSomethingWithPickedFile(BuildContext context) async {
    // Left is an error choosing a file from system, right is a nullable File, null being no file picked
    final Either<PickFileException, File?> fileRes = await pickSingleFile();
    if (fileRes.isLeft()) {
      return RestoreDialogResult.errorFilePermission;
    }
    
    // Here is where I would like to extract the Right value
    final file = fileRes. fold((l) => throw StateError(""), (r) => r);

    if (file == null) {
	  // No file was picked
      return null;
    }
    
    // Continue...
  }
```

**Comment by SandroMaglione** [comment]
@davidmartos96 yes, there is a better way using the `fpdart` API.

As a general rule, remember that `isLeft` (and `isRight`) should be used sporadically, since in most cases you should handle both left and right in a chain.

Here are some general guidelines:
- Return `Task` instead of `Future` ([you can read more here about Task](https://www.sandromaglione.com/techblog/async-requests-future-and-task-dart))
- Use `map` / `mapLeft` to change the values inside `Either`
- Use `flatMap` when you want to extract the value inside an `Either`

Here is a possible alternative solution:
```dart
Future<Either<PickFileException, File?>> pickSingleFile() => ...;

/// 👇 Changed return type
TaskEither<RestoreDialogResult, SomeResult?> _doSomethingWithPickedFile(
        BuildContext context) =>
    /// 1️⃣ Use [TaskEither] to work with async functions
    TaskEither<PickFileException, File?>(pickSingleFile)
    
    /// 2️⃣ `mapLeft` is like `if (isLeft)`
    .mapLeft(
      (_) => RestoreDialogResult.errorFilePermission,
    )
    
    /// 3️⃣ `flatMap` allows you to access the `file`
    .flatMap(
      (file) {
        // Continue
      },
    );
```

Let me know if you need any clarification on the code above. Does this work for you usecase?

**Comment by SandroMaglione** [comment]
@davidmartos96 indeed the package is designed to be used in a chain. You can make the chain longer, adding a check for all the `Left` cases. This always works, although it makes the code a long chain (by design) as you mentioned.

The only "clean" way to extract the value from `Right` would be to specifically check its type:
```dart
if (pickFileRes is Right) {
  /// Now you have access to `pickFileRes.value`
```

Using `isLeft` or `is Left` doesn’t work because dart has no idea that `Either` can be **only** `Right` and `Left`, so it cannot narrow down the type.

This may change after [Patterns lands in dart](https://github.com/dart-lang/language/issues/546), because then `Either` could be defined as and ADT.

Let me know if you need any further help 👍

**Comment by hbock-42** [comment]
Hello @SandroMaglione  and thank you for this amazing lib.
I can read here that I should have access to pickFileRes.value inside an if statement where I tested the option is Right.

It seems this is not possible anymore could you confirm?
I understand why is should not be possible in the first place -> what is the point of doing functional programming if it is to fall back to a more traditional programming pattern?
Still, I can see one place we could benefit from. Since in dart we can now conditionally insert element into lists:
```
final String? title = 'title';
final List<Widget> widgets = [
    if (title != null) Text(title!)
]
```
I am really trying to implement something like that in FP.

What I would see:
```
final Option<String> titleOption = Option.of('title');
final List<Widget> widgets = [
    title.ifSome(title => Text(title))
]
```
But I am pretty sure it is impossible to implement it without modifying dart directly. That is why I wanted to access the value after checking it was there.

**Comment by SandroMaglione** [comment]
@hbock-42 you could use `is`, but you actually need to fully specify the type of `Either`:

```dart
final either = Either<String, int>.of(10);

/// This does not work 👇⛔️
if (either is Right) {
  final a = either.value; /// `dynamic`
}

if (either is Right<String, int>) {
  /// Now you have access to `either.value`
  final a = either.value; /// `int`
}
```

With dart 3 and pattern matching the usability of Either will probably improve, coming soon 🔜

**Comment by hbock-42** [comment]
@SandroMaglione Thank you it does it for me with this :) I wasn't able to retrieve the right value because I was using either.isRight()

**Comment by HasanAlqaisi** [comment]
> @hbock-42 you could use `is`, but you actually need to fully specify the type of `Either`:
> 
> ```dart
> final either = Either<String, int>.of(10);
> 
> /// This does not work 👇⛔️
> if (either is Right) {
>   final a = either.value; /// `dynamic`
> }
> 
> if (either is Right<String, int>) {
>   /// Now you have access to `either.value`
>   final a = either.value; /// `int`
> }
> ```
> 
> With dart 3 and pattern matching the usability of `Either` will probably improve, coming soon 🔜

Hi,
Is that possible now? I still get dynamic if I don't specify the exact type.

**Comment by SandroMaglione** [comment]
@HasanAlqaisi with dart 3 (starting from fpdart v1.0.0) you can use pattern matching to extract the value, specifically the `if-case` syntax:

```dart
final either = Either<String, int>.of(10);
if (either case Right(value: final value)) {
  /// `value` from [Either] type `int`
}
```
