### ISSUE TITLE
Add an extension on`Function` which convert a function that returns `Either` to async one

### ISSUE THREAD

**Issue by fujidaiti** [SandroMaglione/fpdart#77]
Hi! I have a small proposal regarding `TaskEither`.

I konw that i can chain functions that return `TaskEither` using `flatMap`. And it is also possible to chain a function that returns `Either` using `chainEither`.  But I think it would be better to have an extension on `Function` type which convert `Either<L, R> Function(T)` to `TaskEither<L, R> Function(T)`  something like:

```Dart
extension EitherToTaskEither<L, R, T> on Either<L, R> Function(T) {
  TaskEither<L, R> Function(T) get async =>
      (T t) => TaskEither(() async => this(t));
}
```

Then, we can use it as the following:

```Dart
final newTaskEither = taskEither.flatMap(returnsEither.async);
```

This extension duplicates the functionality of `chainEither`, but I think this one is more readable because we can use the same api (`flatMpap`) in context. 

BTW, a very nice library. I can't wait for the day when pattern matching is implemented in Dart and `fpdart` gets more better 😄

**Comment by SandroMaglione** [comment]
Hi @fujidaiti 

I think it would be generally better to avoid adding too many similar methods and extensions to the core library. Once a new method is introduced, it becomes difficult to deprecate it and remove it if needed.

> This extension duplicates the functionality of `chainEither`

This is the reason why I would prefer to leave `fpdart` core just to the main methods that you cannot achieve otherwise, while leaving extensions to specific projects.
