### ISSUE TITLE
How to use chainEither on taskEither

### ISSUE THREAD

**Issue by radikz** [SandroMaglione/fpdart#79]
Hello, I am new to FP and I followed your article and have been stuck for quite a while.
I would like to ask how to chain function using chain either.

```dart
TaskEither<AppError, Response> _request(String url) => TaskEither.tryCatch(
  () async => await dio.get(url),
  (error, stackTrace) => AppError.from(error as Exception),
).chainEither((response) => _validResponseBody(response, AppError.fromResponse));

Either<E, String> _validResponseBody<E>(
    Response response,
    E Function(Response) onError,
) =>
    Either<E, Response>.fromPredicate(
      response,
      (r) => r.statusCode == 200,
      onError,
    ).map((r) => r.data);
```

The error said 
`
The return type 'Either<AppError, String>' isn't a 'Either<AppError, Response<dynamic>>', as required by the closure's context.
`

How to resolve this?
Much appreciated.

**Comment by radikz** [comment]
I already solved it with 
```dart
TaskEither<AppError, Response> _request(String url) => TaskEither<AppError, Response>.tryCatch(
        () async => await dio.get(url),
        (error, stackTrace) => AppError.from(error as Exception),
      ).chainEither(
        (response) => Either.tryCatch(
          () {
            if (response.statusCode != 200){
              Either.left(AppError.fromResponse(response));
            }
            return response;
          },
          (_, __) => AppError.fromResponse(response),
    ),
  );
```

I changed it from **Either.fromPredicate** to **Either.tryCatch**
I am not sure if this is best practice of fp.

**Comment by SandroMaglione** [comment]
Hi @radikz 

In your first example the issue is that `_validResponseBody` returns `Either<E, String>`, while the type on your `TaskEither` is `TaskEither<AppError, Response>` (so `Response` instead of `String`). That's because you are mapping (`map`) the `Response` to `String` using `.map((r) => r.data);`.

Your second example works because in your `tryCatch` you just return `Response` (`return response;`) instead of `response.data`.

Does this make it more clear?

**Comment by radikz** [comment]
Ah right. thanks for the kind response.
Closed for now. ^^
