### ISSUE TITLE
Getter properties to simplify syntax

### ISSUE THREAD

**Issue by abuffery** [SandroMaglione/fpdart#81]
It would be nice to have some easy syntax getter properties of the style of:

```dart
 assert(Some(Some(996)).flatten == Some(996));
```

**Comment by SandroMaglione** [comment]
Hi @abuffery 

Indeed `Option` already has a [flatten constructor](https://pub.dev/documentation/fpdart/latest/fpdart/Option/Option.flatten.html).

The reason this is implemented as a constructor is that in dart there is (yet) no way to know the type of a generic. Therefore, `Some` cannot know that its value `T` is another `Some`. For this to work, dart would need to have **higher kinded types**.

I actually [opened an issue on the dart repository a while ago](https://github.com/dart-lang/language/issues/1655) if you are interested.

Another option would be to define an extension specific for `Option<Option<T>>`:
```dart
extension FpdartFlatten<T> on Option<Option<T>> {
  Option<T> get flatten => Option.flatten(this);
}

final flat = Option.of(Option.of(10)).flatten;
```

I wouldn’t add this to `fpdart` because it is too specific, but you can definitely add this to your project.
