### ISSUE TITLE
Testing Either List

### ISSUE THREAD

**Issue by Babwenbiber** [SandroMaglione/fpdart#9]
I had the problems with darts already and thought you might have a solution for that.
How do I test an Either List type?
Let's say I have the following simple test:

```

import 'package:flutter_test/flutter_test.dart';
import 'package:fpdart/fpdart.dart';

void main() {
  String expectedLeft = "lefti";
  List<int> expectedRight = [1, 2, 3, 4, 5];

  group("test either", () {
    test("test left", () {
      final res = getExpected(true);
      expect(res, Left(expectedLeft));
    });

    test("test right", () {
      final res = getExpected(false);
      expect(res, Either.right(expectedRight));
    });
  });
}

Either<String, List<int>> getExpected(bool isLeft) {
  if (isLeft) {
    return Left("lefti");
  } else {
    return Right([1, 2, 3, 4, 5]);
  }
}


```

The second test failed, because of the deep list inequality (or no deep list equality test).

How do you test this scenario in a simple manner?

**Comment by SandroMaglione** [comment]
Hi @Babwenbiber 

The reason the test fails is that natively dart compares lists by **identity**. This means that dart will **not** compare the elements inside the list but it will check that the two lists are **the same instance** (which is not the case).

There are many solutions to this problem. Generally, you should override the `==` and `hashCode` methods ([like fpdart does for `Either`](https://github.com/SandroMaglione/fpdart/blob/d7300e3d20005dc05ce64e9323881fd5c255d47a/lib/src/either.dart#L372)).

Another solution would be to use [Equatable package](https://pub.dev/packages/equatable).

For lists specifically, you must either implement a custom equality method (that compares by equality and not by identity) or relay on some package that does this already:
- [fast_immutable_collections](https://pub.dev/packages/fast_immutable_collections)
- [kt_dart](https://pub.dev/packages/kt_dart)

Does this answer solve your doubts?

**Comment by Babwenbiber** [comment]
Thanks a lot for the detailed answer.

I am still quite unsure about some points.

I have read many times, that == does compare identity, but `expect([1, 2, 3, 4, 5], [1, 2, 3, 4, 5]);
` yields true. So how does this fit into the story?

Furthermore, I checked out the fast_.. package and couldn't understand how to apply this to either. Can you give me a mini example or best practice on how you write your tests?

Thanks

**Comment by knaeckeKami** [comment]
`expect` does not use `==`, but has a more sophisticated matching method.
See https://github.com/dart-lang/matcher/blob/3a80b989c5c1071d32af11ea9d3fae55807a14c2/lib/src/equals_matcher.dart#L18 , 
and https://github.com/dart-lang/matcher/blob/3a80b989c5c1071d32af11ea9d3fae55807a14c2/lib/src/equals_matcher.dart#L107 in particular.

So, Iterables are compared deeply by expect, even if `==` would return `false` on them.

But you don't give an Iterable to `expect`, you give a Right([1, 2, 3, 4, 5]) to `expect`.  

So `expect` eventually compares the `Either` instances by `==`.
And Either compares the wrapped value by `==`, which will return false, because List don't implement `==`, and since these are two instances of Lists, `==` will return false.


@SandroMaglione suggested using Lists that do implement `==`, for example fast_immutable_collections.

Your would use it like this: `Right(IList([1, 2, 3, 4, 5]));`
I would recommend doing this anyway since mutable collections don't play well with functional programming.

**Comment by Babwenbiber** [comment]
Thanks.
I didn't know people use IList instead of List :)
